# Generated by Django 2.0.2 on 2018-04-26 12:19

import django.core.validators
from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Code')),
                ('class_sec', models.CharField(max_length=100, verbose_name='Class')),
                ('topic', models.CharField(max_length=100, verbose_name='Topic')),
                ('deadline', models.DateField(validators=[teacher.models.validate_date_1], verbose_name='Deadline')),
                ('image', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10, verbose_name='RollNo')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name should not contain digits or special characters.', regex='^[ a-zA-Z]+$')], verbose_name='Name')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('class_sec', models.CharField(max_length=100, verbose_name='Class')),
                ('email', models.EmailField(max_length=254)),
                ('drive_link', models.CharField(max_length=100, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name should not contain digits or special characters.', regex='^[ a-zA-Z]+$')], verbose_name='Name')),
                ('subjects', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name should not contain digits or special characters.', regex='^[ a-zA-Z]+$')], verbose_name='Subjects')),
                ('dob', models.DateField(blank=True, null=True, validators=[teacher.models.validate_date], verbose_name='Date Of Birth')),
                ('image', models.ImageField(upload_to='')),
                ('phone_no', models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'.It must be 7-10 digits long.", regex='^\\+?1?\\d{7,10}$')])),
                ('field_of_interest', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Name should not contain digits or special characters.', regex='^[ a-zA-Z]+$')], verbose_name='Interests')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Querie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name should not contain digits or special characters.', regex='^[ a-zA-Z]+$')], verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('query', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
